### ISSUE TITLE
Super long term prediction

### ISSUE THREAD

**Issue by zaverichintan** [BII-wushuang/Lie-Group-Motion-Prediction#6]
Hello,
I was wondering how to produce the results for 1000 frames output as in the video given on your site?  Could you please upload the trained model? 
I tried to train the model by setting longterm to true and here is my output for walking: [Video](https://gofile.io/d/0Z4T1s)
Thanks in advance.

**Comment by BII-wushuang** [comment]
Hi, you may try with
```python motion_prediction.py --action=walking --longterm=1```
Unfortunately, I do not have the model weights corresponding to the one in the demo video.
Looking at your output, it looks natural. The purpose of this long term forecasting is more for generating natural looking walking motion in the long term (accuracy is not a concern here since it is unreasonable to expect accurate long term predictions in the long term). One problem in previous works was that the generated motion usually converged to a motionless state after a few seconds.

**Comment by zaverichintan** [comment]
Yes. Looks good for the walking action. I agree that the errors won't reduce for long term predictions. For eating action, the long term prediction goes to mean pose, was it same when you performed the experiment?

**Comment by BII-wushuang** [comment]
The eating and smoking action is quite sensitive and contingent on the input sequence. It requires larger variations in the input sequence to have meaningful long term predictions. Due to such stringent conditions, the long term prediction will only default to walking action in the updated code. Otherwise, if the input sequence is changed to include more variations (eg. eating while walking), the long term prediction would work.
