### ISSUE TITLE
The paper and the github topic are inconsistent

### ISSUE THREAD

**Issue by logiclj** [BII-wushuang/Lie-Group-Motion-Prediction#9]
I I found the paper titled Investigating Pose Representations and Motion Contexts Modeling for 3D Motion Prediction, but your github title is Motion prediction with Hierarchical Motion Recurrent Network, and the project name is lie-group-motion-prediction. The paper explicitly uses Stiefel manifold parameterization of rotation instead of lie-group. Or maybe Stiefel manifold parameterization of rotation is the idea of lie-group？ Finally, is the code described in this paper consistent with this github code?
Looking forward to your reply
thank you very much

**Comment by BII-wushuang** [comment]
Thank you for the interest in our work. The code in this current commit corresponds to that for our previous [CVPR 2019](http://openaccess.thecvf.com/content_CVPR_2019/papers/Liu_Towards_Natural_and_Accurate_Future_Motion_Prediction_of_Humans_and_CVPR_2019_paper.pdf) paper. The TPAMI paper [Investigating Pose Representations and Motion Contexts Modeling for 3D Motion Prediction](https://arxiv.org/pdf/2112.15012) is an extension to the CVPR work but we have yet to push the commits onto this repository. I will do so in the near future.

**Comment by BII-wushuang** [comment]
FYI, in the CVPR work and the current commit, we used axis angles (equivalent to the lie algebra so(3)) to parameterize 3D rotations, i.e. the SO(3) lie group. In the follow-up extension, we compared axis angles, quaternions, and Stiefel manifolds to parameterize 3D rotations, where the Stiefel manifold parameterization is deemed superior due to it being globally continuous over the entire SO(3) manifold as well as more being less expensive for computing geodesic losses / forward kinematics.

**Comment by logiclj** [comment]
Thank you very much for your reply, sorry to bother you. After reading your paper, it helped me a lot. I have a small question, at the end of the first paragraph in section 4.3 of your paper, why is R1 and R3 more similar, I'm sorry I didn't find the relevant material to prove this.

**Comment by BII-wushuang** [comment]
> Thank you very much for your reply, sorry to bother you. After reading your paper, it helped me a lot. I have a small question, at the end of the first paragraph in section 4.3 of your paper, why is R1 and R3 more similar, I'm sorry I didn't find the relevant material to prove this.

For this example, R1 is given by the axis angle parameters $(0.01,0,0)^T$; R2 is given by the axis angle parameters $(0.5,0,0)^T$; while R3 is given by the axis angle parameters $(6.27,0,0)^T$. Essentially, R1, R2 and R3 are all rotations about the x-axis, with R1 rotating 0.01 radians; R2 rotating 0.5 radians, and R3 rotating 6.27 radians. Since rotation is periodic for 2 Pi radians, the rotation of R3 is approximately -0.01 radians. Therefore R1 and R3 are much more similar rotations/orientations.

**Comment by logiclj** [comment]
Wow, I see, thanks again. Your paper helped me a lot, and your code will help even more. Hope to see the code soon. I wish you a happy life, good work and more top articles.
